#@TYPE: Machine
#@NAME: Haridwar Board BSP
#@SOC: AM62x
#@DESCRIPTION: Machine configuration for Haridwar board

require conf/machine/include/k3r5.inc

SYSFW_SOC = "am62x"
SYSFW_CONFIG = "evm"

PREFERRED_PROVIDER_virtual/bootloader = "u-boot"
PREFERRED_PROVIDER_u-boot = "u-boot"