#@TYPE: Machine
#@NAME: Haridwar Board BSP
#@SOC: AM62x
#@DESCRIPTION: Machine configuration for Haridwar board

require conf/machine/include/ti-extras.inc

SYSFW_SOC = "am62x"
SYSFW_CONFIG = "evm"

UBOOT_SUFFIX = "bin"
UBOOT_BINARY = "tiboot3.${UBOOT_SUFFIX}"

SOC_FAMILY = "ti-soc"
KERNEL_DTB_OVERLAY_SUPPORT ?= "1"
require conf/machine/include/soc-family.inc
SOC_FAMILY:append = ":k3r5"

# The closest of existing tunes for Cortex-R5F
DEFAULTTUNE = "armv7athf"
# require conf/machine/include/arm/armv7a/tune-cortexa8.inc
# PREFERRED_PROVIDER_virtual/kernel = "linux"
PREFERRED_PROVIDER_virtual/bootloader = "u-boot"
PREFERRED_PROVIDER_u-boot = "u-boot"