#@TYPE: Machine
#@NAME: Haridwar Board BSP
#@SOC: AM62x
#@DESCRIPTION: Machine configuration for Haridwar board

require conf/machine/include/am62xx.inc

KERNEL_DEVICETREE_PREFIX = " \
    ti/k3-am625 \
    ti/k3-am62x-sk \
"

KERNEL_DEVICETREE = " \
    ti/k3-am625-sk.dtb \
"

PREFERRED_PROVIDER_virtual/bootloader = "u-boot"
PREFERRED_PROVIDER_u-boot = "u-boot"

FIT_CONF_DEFAULT_DTB = "k3-am625-sk.dtb"

UBOOT_MACHINE = "am62x_evm_a53_defconfig"

WKS_FILE = "sdimage-squashfs.wks.in"

DISTRO_FEATURES:remove = "3g \
            irda \
            nfc \
            zeroconf \
            3g \
            bluetooth \
            nfc \
            nfs \
            gnome-desktop-testing \
            python-setuptools \
            python3-core \
            qemu"