# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a packages directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "eaton"
BBFILE_PATTERN_eaton := "^${LAYERDIR}/"
BBFILE_PRIORITY_eaton = "4"
LAYERSERIES_COMPAT_eaton = "wrynose"

TI_COMMON_DEPLOY ?= "${TOPDIR}/tmp/deploy"
DEPLOY_DIR_IMAGE:ti-soc = "${TI_COMMON_DEPLOY}/images/${MACHINE}"

LICENSE_PATH += "${LAYERDIR}/licenses"